### ISSUE TITLE
[BUG] Getting Something went wrong while uploading photo

### ISSUE THREAD

**Issue by ApoorvTyagi** [b3nab/instapy-cli#105]
Getting 400 Bad request
```python
with client(username, password) as cli:
   cli.upload(image, text)
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by SteBurz** [comment]
I've made a video about his here [why the instagram automation will fail.](https://youtu.be/V09fW6ZRraE)
I think this repo needs to be updated to the new API or the official API needs to be opened up (if this hasn't already happend).
