### ISSUE TITLE
Problem with blank spaces while uploading

### ISSUE THREAD

**Issue by addius8** [b3nab/instapy-cli#16]
Hey there,

im quite new to Python :). I really love your library.
But somehow when Im uploading like this:

``` python
contenttext = 'welcome to our Instagram'
subprocess.call('instapy -u {0} -p {1} -f {2} -t {3}'.format(accname1, pw1, path, str(contenttext)))
```

the program just uploads the text: "welcome" and nothing else :( it somehow misses everything beyond the blank space. 
What am I doing wrong?

**Comment by sharegrams** [comment]
Hey I was wondering how I'd do line breaks in the captions? @b3nab
