### ISSUE TITLE
Add Story

### ISSUE THREAD

**Issue by khalilst** [b3nab/instapy-cli#2]
Actually I want to know is there any way to add a story/a story with tag using instapy-cli?

However I appreciate your great work. It works like a charm.

**Comment by b3nab** [comment]
Thank you man, it's fulfilling for me to hear your satisfaction. :)

On what you wrote: this could be a great feature, however there are some obstacles to manage.

- 1. The first is that we need some tools to intercept/sniff instagram app's traffic (android/ios). 
- 2. Then post some datas to stories and log the traffic intercepted so we can see how the call to API is composed and we could replicate it on instapy-cli.
- 3. Code the endpoints/datas to instapy-cli and release a new feature.

This is the process of reverse-engineering any private API (like in this case for Instagram) from an android/ios app. And with this process we can integrate other functions, like post a story, post a video or send a message.

It's not so complex to do but it need a bit of time.
Anyone who want to collaborate (even only sniffing datas structure and endpoints) is welcome. 🥂

**Comment by b3nab** [comment]
From v0.0.7 there is the support for story, only via a python script (not in cli implemented yet).
This is a feature not well tested, so if there is a problem submit a new issue.

🥂
