### ISSUE TITLE
is possible to use a cookie ?

### ISSUE THREAD

**Issue by ilmetu** [b3nab/instapy-cli#20]
Will be possible to use a cookie instead passing user and password?

Thanks

**Comment by b3nab** [comment]
I'm trying to accomplish something similar to this, so you don't have to re-login, but I'm searching, yet. 

Any suggestion and talks about code will be appreciated.

**Comment by b3nab** [comment]
From v0.0.7 there is already an implementation of the cookie mechanism using a file "ig.json" to avoid re-login.
🥂
