### ISSUE TITLE
Is it possible to add images and captions from a csv file at specific daily intervals? 

### ISSUE THREAD

**Issue by MrBeardedGuy** [b3nab/instapy-cli#24]
I was wondering if it's possible to add images and captions from a csv file at specific daily intervals

**Comment by b3nab** [comment]
I think yes, of course.
You can code your function, parse your csv file and use cron or some other python library to fire-up another function that simply use instapy-cli with your username, password and the correct file path from your csv.

But instapy-cli is not created to solve this problem.
