### ISSUE TITLE
Caption not appearing

### ISSUE THREAD

**Issue by maisagent** [b3nab/instapy-cli#29]
Hi,
the caption stopped posting with the image at exactly midnight today. It only posts the images. Im crating a new client instance for every upload so that cant be the problem. Script was unchanged for days. i'll be testing tomorrow to see whats wrong but i thought i might give u a early heads up if the api changed or something like that. Thanks for creating this tool

**Comment by maisagent** [comment]
ok started working again spontaneously... Dont know what happend there... any ideas?

**Comment by b3nab** [comment]
I don't know, maybe some API endpoints changed but I am not sure about this.
Actually all things work fine.
