### ISSUE TITLE
Options for automatic sharing on Facebook/Twitter/Tumblr

### ISSUE THREAD

**Issue by JohanM87** [b3nab/instapy-cli#31]
Hi!

This program is very usefull, thanks for sharing!

Would it be possible to add the options like in the Instagram-app for automaticly share a new Instagram-post to Facebook/Twitter/Tumblr? 

Thanks,
Johan.

**Comment by sharegrams** [comment]
use IFTTT

**Comment by b3nab** [comment]
Hi @JohanM87 , please follow @sharegrams 's suggestion and use IFTTT to auto-share your new ig post to other socials.

This is not a function of instapy-cli, so I'm going to close this issue.

Have a good day, 🥂
