### ISSUE TITLE
Just the first word

### ISSUE THREAD

**Issue by rasiqueira** [b3nab/instapy-cli#35]
Thank you for the lib. It´s amazing.

I had a problem with the text. For example:

instapy -u USR -p PSW -f FILE/LINK -t 'TEXT CAPTION'

I just post"TEXT". I can´t get the other words.

**Comment by b3nab** [comment]
Maybe it's the string quotation that need to be changed from 'X' to "X"? (or viceversa?)

**Comment by b3nab** [comment]
Please, reopen this issue if you get the same problem and add other useful details and your specific code.
🥂
