### ISSUE TITLE
upload photo does not work

### ISSUE THREAD

**Issue by du-phan** [b3nab/instapy-cli#36]
Hi, I'm testing the `upload()` function, even though it returned "Done", the photo was not uploaded. 
However if I added the flag `story=True`, it works for the instagram story.

**Comment by b3nab** [comment]
Sounds weird. 
Can you provide other info via `instapy` terminal output to check instapy-cli and python version.
Can be helpful to know how you use it, so please provide your code or an example very similar to it.

**Comment by b3nab** [comment]
If the problem continue please provide some other infos such as the account creation date, errors, instapy-cli and python version and a sample code to inspect the problem.
Thanks.
🥂
