### ISSUE TITLE
Upload image as story, incompatible real aspect ration

### ISSUE THREAD

**Issue by giorizzotti** [b3nab/instapy-cli#37]
Hi, I'm trying to upload an image to a story whose resolution is 1080x1920 which should be the best resolution for IG Stories, as stated in a lot of blog, such as in this extract:

> Instagram story dimensions are 1080px wide by 1920px tall. Portrait photos and videos taken on your smartphone will be 1080 pixels wide by 1920 pixels in height, while other photos and videos should be reformatted to fit these dimensions. This is also known as a 9:16 aspect ratio.

I get the following error:

> warnings.warn('This endpoint has not been fully tested.', UserWarning)
> Error is >>
>     Incompatible reel aspect ratio.
> 
> Something went bad.
> Please retry or send an issue on https://github.com/b3nab/instapy-cli

**Comment by b3nab** [comment]
You missing copy the first line of instapy-cli output. What is the version of instapy-cli and python?

**Comment by giorizzotti** [comment]
These: instapy 0.0.8.2  |  python 3.7.2

**Comment by b3nab** [comment]
Yes you are right. This seems a bug in the instagram-private-api-extensions/media.py file.
I'm trying to do a small edit to patch this issue and refer this to @ping that is the maintainer of that project (or maybe prepare a PR to fix this issue for all and for ever.)

Thanks for reporting @giorizzotti 
I'll reply when will be some news.

**Comment by b3nab** [comment]
I'm releasing a new version `0.0.8.3` to fix this issue. 

Hope you'll have a better experience since this new release.
🥂

**Comment by mo-username** [comment]
@b3nab Sir, I don't know if it's the proper way to ask this, but is it possible to upload a story (image) with a link (IGTV video link)? Thank you!
