### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f4bb' in position 0

### ISSUE THREAD

**Issue by macdonjo** [b3nab/instapy-cli#4]
The trace isn't necessarily helpful, but here it is:

```
Traceback (most recent call last):
  File "/usr/local/bin/instapy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/instapy_cli/__main__.py", line 11, in main
    print(welcome_msg)
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f4bb' in position 0: ordinal not in range(128)
```

**Comment by macdonjo** [comment]
Okay for some reason this library prints out a welcome message with emojis for no real reason,

**Comment by b3nab** [comment]
Hi @macdonjo ,
We live in 2017, unicode is the standard.

Please use a terminal with support for unicode character and emoji (default if unicode is supported).

**Comment by DyingEcho** [comment]
I think there should be a way to remove the welcome message, or at least the emoji from it. Not everyone has an emoji-capable terminal with bitmap support.

**Comment by b3nab** [comment]
I notice that you use python 2.7, maybe this is the problem. 
I'll test it out and eventually (this is not my first option) remove the emoji from the client. 

Info soon..

**Comment by b3nab** [comment]
I found a solution good for all: remove emoji package and add (in the near future) some ascii art instead of emoji, so this will bring support to everyone on every platform and keep this package "fun" as it should be. 

You could find a new version on pip. I close this issue, open a new one if there are other problems.
🥂
