### ISSUE TITLE
[F+] Create config file in fixed directory

### ISSUE THREAD

**Issue by vitorgalvao** [b3nab/instapy-cli#51]
**Is your feature request related to a problem? Please describe.**

By creating the [`ig.json`](https://github.com/b3nab/instapy-cli/blob/936de73c942999d0ceb5ae44cf9bc03337669b29/instapy_cli/cli.py#L11) wherever the script is run, `instapy-cli` is polluting the user’s system (likely the home) and not taking advantage of the config if it already exists in another directory.

**Describe the solution you'd like**

The config file should be stored in a fixed location, either following the XDG Base Directory specification, or at the very least in the fixed `~/.config/instapy-ci/ig.json`.

To support for multiple cookies/logins (I have no use for, but it seems to be one of the goals of the project), there could be a command line flag (`--cookie`, `-c`) that takes a path as the argument to save/read from. Even in that case, there should be a default location.

**Describe alternatives you've considered**

My current workaround is to wrap the tool in a script, and `cd` to a fixed directory before running the tool:

```
config_dir="${HOME}/.config/instapy-cli"
[[ -d "${config_dir}" ]] || mkdir -p "${config_dir}"
cd "${config_dir}" || exit 1
```

**Additional context**

N/A

**Comment by b3nab** [comment]
Are you using instapy-cli from cli interface or via a python script that you run?

**Comment by vitorgalvao** [comment]
From CLI interface.

**Comment by b3nab** [comment]
I updated the programming interface to not overload the user system with cookie files. 
Actually the cli is not updated with last edits. However I plan that in the next versions (0.0.12 or 0.0.13) it will be available multiple options to use cookie, save or not a cookie_file or provide you the path.

Stay tuned 👍
