### ISSUE TITLE
instapy-cli installation error

### ISSUE THREAD

**Issue by pcesar-costa** [b3nab/instapy-cli#55]
Hi, I'm trying to install de package instapy-cli, however the error occured:

`(base) PS C:\Users\web> pip install instapy-cli
Collecting instapy-cli
  Using cached https://files.pythonhosted.org/packages/ac/32/4dd2ac6c4e48bfba9bb387b6d4049b039865596adb2b99aca1058f5938e5/instapy_cli-0.0.12-py2.py3-none-any.whl
Collecting filetype==1.0.5 (from instapy-cli)
  Using cached https://files.pythonhosted.org/packages/1c/78/047cf0f371f8faafab05b5062f902d4bedd945d436544b30db692622ab84/filetype-1.0.5-py2.py3-none-any.whl
Requirement already satisfied: requests>=2 in c:\programdata\anaconda3\lib\site-packages (from instapy-cli) (2.21.0)
Collecting instagram-private-api-extensions==0.3.8 (from instapy-cli)
  Using cached https://files.pythonhosted.org/packages/fb/3a/f9e594ab71d17f2deb59ab94c901914bc69a3b229b496c4cd70c5e89d6de/instagram_private_api_extensions-0.3.8-py3-none-any.whl
Requirement already satisfied: instagram-private-api==1.6.0 in c:\programdata\anaconda3\lib\site-packages (from instapy-cli) (1.6.0.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2->instapy-cli) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2->instapy-cli) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2->instapy-cli) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2->instapy-cli) (1.24.1)
Requirement already satisfied: Pillow>=4.0.0 in c:\programdata\anaconda3\lib\site-packages (from instagram-private-api-extensions==0.3.8->instapy-cli) (5.4.1)
Collecting moviepy==0.2.3.2 (from instagram-private-api-extensions==0.3.8->instapy-cli)
  Using cached https://files.pythonhosted.org/packages/e4/1f/fb4b8d9397f7952fcb594cb5df3061f00debae7ea92b3be9881c18b905ab/moviepy-0.2.3.2-py2.py3-none-any.whl
Requirement already satisfied: tqdm==4.11.2 in c:\programdata\anaconda3\lib\site-packages (from moviepy==0.2.3.2->instagram-private-api-extensions==0.3.8->instapy-cli) (4.11.2)
Collecting imageio==2.1.2 (from moviepy==0.2.3.2->instagram-private-api-extensions==0.3.8->instapy-cli)
Requirement already satisfied: decorator==4.0.11 in c:\programdata\anaconda3\lib\site-packages (from moviepy==0.2.3.2->instagram-private-api-extensions==0.3.8->instapy-cli) (4.0.11)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from moviepy==0.2.3.2->instagram-private-api-extensions==0.3.8->instapy-cli) (1.16.2)
Installing collected packages: filetype, imageio, moviepy, instagram-private-api-extensions, instapy-cli
  Found existing installation: imageio 2.5.0
Cannot uninstall 'imageio'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

Someone can help me? I tried to uninstall manually the imageio package, but the error still occurs.

**Comment by b3nab** [comment]
Hi @pcosta21 , try to install not from cache. Search on google how to install pip packages without using the cache.

🥂
