### ISSUE TITLE
[BUG] Cant upload photos 

### ISSUE THREAD

**Issue by iHeist** [b3nab/instapy-cli#58]
So, I was getting an error when uploading videos but was able to fix it with the solution provided in #46 by @salahar9 and it worked, but now I cant upload photos, this is the error that I'm getting 

> Error is >>
>     Media is not a recognized file type, use only images and videos.
> 
> Something went bad.
> Please retry or send an issue on https://github.com/b3nab/instapy-cli
> 
> Traceback (most recent call last):
>   File "C:\Users\iHeist\Documents\python projects\Instagram_bot\menu.py", line 118, in <module>
>     print(menu())
>   File "C:\Users\iHeist\Documents\python projects\Instagram_bot\menu.py", line 100, in menu
>     images()
>   File "C:\Users\iHeist\Documents\python projects\Instagram_bot\menu.py", line 66, in images
>     cli.upload(image, text)
>   File "C:\Users\iHeist\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy_cli\cli.py", line 153, in upload
>     raise IOError("Unable to upload.")
> OSError: Unable to upload.

my system
 - OS: Windows 10
 - Python: 3.7.4 - 64 bits
 - instapy-cli Version: 0.0.12

I attached the image that i'm trying to upload
![image1](https://user-images.githubusercontent.com/53238611/62391812-7739ab00-b52b-11e9-8fdc-5c605ae9ce74.jpg)

**Comment by tomdaly** [comment]
@iHeist 
Hi, I think I have a fix for this - if you could test it out in the same way that you did when fixing the other issue and report back then that would be great, and I can commit the modifications.

As the comment in #46 mentions, make sure you've already completed these steps:
At the top of the `media.py` file add
`import magic`
then change the check_type function to this:
```
def check_type(self):
    self.media_ext = magic.from_file(self.media_path,mime=True)
    self.media_ext=  self.media_ext.split('/')[1]
```

Once that's done, try changing what will now be line 36:
```    
def is_image(self):
    return True if self.media_ext in ['jpg', 'png', 'gif'] else False
```
to this:
```
def is_image(self):
    return True if self.media_ext in ['jpg', 'jpeg', 'png', 'gif'] else False
```

Adding the 'jpeg' extension should fix it (as your file ends in .jpeg, not .jpg). Let me know if this works and I'll commit the changes :+1:

**Comment by iHeist** [comment]
@tomdaly Thank you, I did a test and it worked perfectly, I was able to upload a photo and a video without any type of issue. Thanks for the help.

**Comment by esTse** [comment]
I can't locate the file media.py, I'm using Raspbian as SO.
