### ISSUE TITLE
NameError: global name 'instapy_cli' is not defined

### ISSUE THREAD

**Issue by marteaurouge** [b3nab/instapy-cli#6]
Not sure this is a bug, but I had trouble uploading some pics today, so i updated the project via pip,

now i get this "NameError: global name 'instapy_cli' is not defined" ; not sure what to do!

**Comment by b3nab** [comment]
Hi @marteaurouge,
please explain how do you get this error and what steps you done, this could led to replicate your problem and help you find a solution. 😄

**Comment by marteaurouge** [comment]
I had some errors on a previous version (not sure of the errors, cause now i updated). It worked fine before.

So i updated the app with a sudo pip install --upgrade (i'm under the latest version of ubuntu),

and now the error i get is:

> Traceback (most recent call last):                                                                                                                                           
>   File "/usr/local/bin/instapy", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/instapy_cli/__main__.py", line 10, in main
>     print('instapy-cli v.' + instapy_cli.__version__)
> NameError: global name 'instapy_cli' is not defined

I didn't change anything to the way i use the soft:
instapy -u username -f filename -t "your text"

**Comment by 5in4** [comment]
Same for me after installing this package from pip.
This issue is already fixed in #[this commit](https://github.com/b3nab/instapy-cli/commit/6c88f78007fb018f13cf612c246746dfae41b65a#diff-5fde3a4e24e5db9ca80d1a9794e97789)

Installing from git is working as expected.

**Comment by b3nab** [comment]
@marteaurouge  @5in4 
Refer to last stable version of instapy-cli (0.0.3) downloading it from pip instead of cloning it from git. 
I updated it now, no more NameError will came out.
If there are any other problems, please open a new issue. I'm closing this one. 
🥂
