### ISSUE TITLE
Issue with v.0.0.3 - IOError: checkpoint_required

### ISSUE THREAD

**Issue by marteaurouge** [b3nab/instapy-cli#7]
Hey There! :)

installed the v.0.0.3 via pip, and i get this error now:

> instapy-cli v.0.0.3                                                                                                                                                          
> Python version: 2.7.14
> use >> instapy -u <USERNAME> -p <PASSWORD> -f <IMAGE.JPG> -t <CAPTION>
> Traceback (most recent call last):
>   File "/usr/local/bin/instapy", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/instapy_cli/__main__.py", line 36, in main
>     with client(options.username, password) as cli:
>   File "/usr/local/lib/python2.7/dist-packages/instapy_cli/cli.py", line 9, in __init__
>     self._session.login(username, password)
>   File "/usr/local/lib/python2.7/dist-packages/instapy_cli/api/session.py", line 66, in login
>     raise IOError(resp_json.get('message'))
> IOError: checkpoint_required

using the app to upload a picture via:
instapy -u username -p pass -f filename -t "your text"

thanks for your work!

**Comment by b3nab** [comment]
Hi @marteaurouge the library works fine, it's a step that Instagram add to verify that you are a human and not a bot.
You have to verify your account (I think from Instagram app..)
Please for other informations search on Google or refer to this link on Quora http://www.quora.com/What-does-checkpoint-required-mean-on-Instagram

Keep in mind that Instagram don't want you to automatize the upload process to prevent scheduling your posts. So dont try to do a mass upload within 30 sec. (Just to say)

I'll close this issue, for other questions open a new one.
🥂
