### ISSUE TITLE
What is the format of instagram cookie ?

### ISSUE THREAD

**Issue by johackim** [b3nab/instapy-cli#70]
Hello,

With what to export instagram cookie ? I know is json file, but what is inside ? Do you have any example of the json format ? I exported with multiple browser addons but it's not work.

Thanks !

**Comment by molnarjani** [comment]
Hi @ston3o

I think it's non-trivial to manually craft that cookie, you can use https://github.com/instagrambot/instapy-cli/blob/master/examples/login-cookie-write-file.py
example to write the cookie to a file.

Hope this helps!

**Comment by johackim** [comment]
Hello @molnarjani,

Exactly what I want ! Thanks !
