### ISSUE TITLE
[BUG] Certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

### ISSUE THREAD

**Issue by Marma92** [b3nab/instapy-cli#72]
Hello, when I run my script, using instapy-cli on my PC I don't encounter any issue. However, on my mac, here is the error thrown: 

> ClientError URLError <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)> (Code: 0, Response: )

**To Reproduce**
Code to reproduce the behavior is a classic one:

```python
with client(username, password) as cli:    cli.upload(filepath, text)
```
(Entire code can be seen [here](https://github.com/Marma92/SPP/blob/master/photopost.py) )

**Env :**
 - OS: macOS
 - Python: 3.7
 - instapy-cli Version:  0.0.12.0

**Comment by Marma92** [comment]
Since it seems more related to the requests package, I'm closing this issue, suggesting to anyone encountering a similar issue to look for it, it's fairly documented.

**Comment by gogs85** [comment]
Hi I have the same issue and use Python 3.8
