### ISSUE TITLE
OSError: Uploaded image isn't in the right format

### ISSUE THREAD

**Issue by dovshmuel** [b3nab/instapy-cli#8]
Whenver I try to use this tool, it gives me "OSError: Uploaded image isn't in the right format" even though the picture is a .jpg file and the resolution is 1080px x 1080px, any ideas what is going wrong?

**Comment by marteaurouge** [comment]
maybe upload a version of your image to check? your software may have saved it with a .jpg extension but the content is actually another format. 

1080x1080 should be good, i think, instagram doesnt like landscape ratio that much ; did you try to upload it cropped to something like 1080x800 ?

**Comment by b3nab** [comment]
Hi @dovshmuel , did you found a solution based on what @marteaurouge wrote?

In case you didn't yet solved the problem, you can try to upload the image in this repo and then reply to us. 👍

**Comment by b3nab** [comment]
@dovshmuel  
I confirm that the aspect ratio should be 4:3. The dimension itself isn't so important. 
In this format surely you can upload every photo you want.
🥂
