### ISSUE TITLE
[BUG] unable to upload picture and i am tired to try run this script please fix this bug 

### ISSUE THREAD

**Issue by RashminDungrani** [b3nab/instapy-cli#80]
No handlers could be found for logger "instagram_private_api.errors"
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File ".\test_instapy.py", line 7, in <module>
    cli.upload(photo)
  File "C:\Python27\lib\site-packages\instapy_cli\cli.py", line 153, in upload
    raise IOError("Unable to upload.")
IOError: Unable to upload.

**Comment by Marma92** [comment]
Please read other people's issues. The "bug" is not the fact of this only library. It seems like IG changed its private API, and until someone updates this library, it won't be working anymore.
