### ISSUE TITLE
OSError: Unable to upload Image.

### ISSUE THREAD

**Issue by samelakshay** [b3nab/instapy-cli#81]
CODE:
=====
`from instapy_cli import client
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

username = 'USERNAME'
password = 'PASSWORD'
image = 'docs/I love you.png'
text = 'This will be the caption of your photo.' + '\r\n' + 'You can also use hashtags! #hash #tag #now'

with client(username, password) as cli:
    cli.upload(image, text)
`

I was using code in upload-a-photo.py in the examples folder of this repo. But, I get the following errors:

`  File "/Users/mac/Desktop/instaAuto/upload-a-photo.py", line 11, in <module>
    cli.upload(image, text)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.`

I used all the solutions which are given here but, none of them work for me except ssl certificate issue. Is this because of my OS or There is really something wrong? 

OS: Mac OS X 10.11.6

**Comment by dalmanza** [comment]
Hi there already bug reported: https://github.com/instagrambot/instapy-cli/issues/79#issue-525916656

**Comment by samelakshay** [comment]
Thanks, but there is no solution there!
