### ISSUE TITLE
Unable to upload photo on insta.

### ISSUE THREAD

**Issue by imvickykumar999** [b3nab/instapy-cli#99]
[IG] not found cookie/cookie_file >> login as default
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-13-49ae7381fa1f> in <module>
      5 text = 'Happy BirthDay Sundar Pichai...' + '\r\n' + 'This photo is uploaded using instabot library of Python. "It is Important to Follow Your Dreams and Heart. Do Something that Excites You. ― Sundar Pichai"'
      6 with client(username, password) as cli:
----> 7     cli.upload(image, text)

~\Anaconda3\lib\site-packages\instapy_cli\cli.py in upload(self, file, caption, story)
    151                 print('Done.')
    152             else:
--> 153                 raise IOError("Unable to upload.")
    154             return res

OSError: Unable to upload.

**Comment by dsqalli2** [comment]
Have you been able to solve the issue?

**Comment by afrtite00** [comment]
Hi ! did you solve it , I'm trying to upload videos but there is no other lib that supports that, can you help me with that

**Comment by imvickykumar999** [comment]
> Hi ! did you solve it , I'm trying to upload videos but there is no other lib that supports that, can you help me with that

Yes, I have solved it.

https://github.com/imvickykumar999/Auto-Upload-Photo-on-Instagram/blob/main/instaphoto.py

**Comment by afrtite00** [comment]
thanks
